### ISSUE TITLE
[solved] Gosu does not build on Ubuntu with documented dependencies 

### ISSUE THREAD

**Issue by petervandenabeele** [hybridgroup/kidsruby#37]
With the documented dependencies of version 1.0.3. Gosu does not build on Ubuntu 10.04.

The error message is:

```
Installing gosu (0.7.41) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /home/peterv/.rvm/rubies/ruby-1.9.3-p0/bin/ruby extconf.rb 
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/jlnr/gosu/wiki/Getting-Started-on-Linux
...
WindowX.cpp: In function ‘void Gosu::screenMetrics(int*, int*, int*, int*)’:
WindowX.cpp:46: error: ‘XineramaScreenInfo’ was not declared in this scope
WindowX.cpp:46: error: ‘screen_info’ was not declared in this scope
WindowX.cpp:46: error: ‘XineramaQueryScreens’ was not declared in this scope
make: *** [WindowX.o] Error 1
...
```

Based on the list in https://github.com/jlnr/gosu/wiki/Getting-Started-on-Linux ,
I executed this command:

```sudo apt-get install build-essential freeglut3-dev libfreeimage-dev libgl1-mesa-dev libopenal-dev libpango1.0-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsndfile-dev libxinerama-dev
...
The following NEW packages will be installed:
  freeglut3-dev libmikmod2 libmikmod2-dev libsdl-mixer1.2 libsdl-mixer1.2-dev libsmpeg-dev libsmpeg0 libxinerama-dev
  x11proto-xinerama-dev
...

```

Once this was executed, `bundle install` succeeded with
```

...
Installing gosu (0.7.41) with native extensions
...

```

I will make a pull request for a short note in the documentation.

```
